# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApiDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApiDemo
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'NewsApiDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsApiDemoUITests' do
    # Pods for testing
  end

end
